spring:
  application:
    name: portfolio-backend
  profiles:
    active: dev
  config:
    import: optional:classpath:secret.properties

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  admin:
    username: ${ADMIN_USERNAME:}
    password: ${ADMIN_PASSWORD:}