spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

app:
  cors:
    allowed-origins: https://rorsat-hafis-portfolio-app.onrender.com
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.springframework.security: WARN